# Generated by Django 3.0.8 on 2020-07-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=30)),
                ('PubgID', models.TextField(max_length=20)),
                ('City', models.TextField(max_length=110)),
                ('District', models.TextField(max_length=110)),
                ('State', models.TextField(max_length=110)),
                ('Pic', models.FileField(upload_to='static')),
            ],
        ),
    ]
