# Generated by Django 3.0.8 on 2020-07-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='whats',
            field=models.TextField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
