# Generated by Django 3.0.8 on 2020-08-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200808_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Disc',
            field=models.CharField(max_length=2000),
        ),
    ]
