# Generated by Django 3.0.8 on 2020-08-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20200808_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='City',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='District',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='State',
            field=models.TextField(max_length=20),
        ),
    ]
